### ISSUE TITLE
Release checklist for clangd 18

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1948]
Using the [Release checklist](https://github.com/clangd/clangd/wiki/Release-checklist) from the wiki as a template:

## Once the release branch is created

- [x] https://github.com/llvm/clangd-www/pull/96
- [x] https://github.com/llvm/llvm-project/pull/84436
- [x] Document any notable new features on the clangd website [none for this release]

## Once the LLVM release is out

- [x] Prepare the clangd release on the Github releases page

**Comment by HighCommander4** [comment]
> LLVM 18.0.1 has been released. Can we get corresponding clangd release please?

@kadircet could you help with this?

(And if you could write down the steps needed to do this at https://github.com/clangd/clangd/wiki/Release-checklist for future reference, that would be great!)

**Comment by HighCommander4** [comment]
> I tried to build my own from LLVM source, but certain features like clang-tidy don't seem to work when built in that way.

Note that you can also get binaries from a couple of other sources:

 * The LLVM release pages (e.g. https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.0, https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.1) have binary packages that include clangd. They're not uploaded immediately for every architecture/OS combination, but it tends to happen sooner than clangd's Github releases.
 * For Linux, from https://apt.llvm.org/

**Comment by konradsa** [comment]
What's the holdup here? This is an amazing project, but not being on top of releasing new versions in sync with LLVM is really hurting it IMHO. Don't you have a nightly CI build that just needs to be released?

Like I said, I know the other sources for the binary and I can also build it myself from LLVM repos. But for some reason, they don't work as well, especially wrt to clang-tidy integration. Can anybody explain what the difference is? Are there certain compiler flags that need to be set to fully enable it?

**Comment by konradsa** [comment]
Not trying to come off too strong here, just genuinely curious. I think you guys are doing an amazing job, my life as a C++ developer would be a lot less productive without clangd. Keep up the amazing work!!!

**Comment by HighCommander4** [comment]
> Like I said, I know the other sources for the binary and I can also build it myself from LLVM repos. But for some reason, they don't work as well, especially wrt to clang-tidy integration. Can anybody explain what the difference is? Are there certain compiler flags that need to be set to fully enable it?

I don't have a guess off the top of my head, but if you file an issue with reproduction steps (i.e. where you're getting the build from or how you're building it, and what doesn't work) I'm happy to try and take a look.

**Comment by HighCommander4** [comment]
>    * [ ]  Document any notable new features on the clangd website

I looked through the release notes to see if anything there should be additionally documented on the clangd website (e.g. on the "Features" page), and nothing jumped out at me. (The Features page could use some general expansion, e.g. having a section on Inlay Hints, but that's an orthogonal issue.)

So I'm going to consider this checklist item done.

**Comment by HighCommander4** [comment]
> Don't you have a nightly CI build that just needs to be released?

We definitely don't have a **nightly** CI build. We do have a [Github Action](https://github.com/clangd/clangd/blob/master/.github/workflows/autobuild.yaml) which runs weekly to produce snapshot releases of trunk.

I'm not sure how the actual release binaries are produced. (It's not just a case of tagging one of the snapshot releases, since the snapshot releases are from trunk and the actual releases are from a release branch.) This is why I asked that we document the steps in the release checklist.

**Comment by HighCommander4** [comment]
> I'm not sure how the binaries for final (non-snapshot) releases are produced. (It's not just a case of tagging one of the snapshot releases, since the snapshot releases are from trunk and the final releases are from a release branch.) This is why I asked that we document the steps in the release checklist.

Based on [this comment](https://github.com/clangd/clangd/issues/1791#issuecomment-1767881684), it sounds like it's done by a manual invocation of the same Github Action that produces the weekly snapshots. However, I'm not sure how to point that to the LLVM 18.x release branch. (There is a dropdown for selecting the branch, but it selects a branch of **this** repository, not the llvm-project repository.)

**Comment by HighCommander4** [comment]
It turns out we do have documentation for this at https://github.com/clangd/clangd/blob/master/releases.md!

I tried to follow that to create https://github.com/clangd/clangd/releases/tag/18.1.2, though at the moment that only has source assets. The docs says "Creating the release will trigger the `autobuild` workflow", but I'm not seeing that happening.

**Comment by nachovizzo** [comment]
Any reason why the new release doesn't have binaries :eyes: ?

**Comment by HighCommander4** [comment]
> Any reason why the new release doesn't have binaries 👀 ?

Well, as described in my previous comment, I tried to create a release but it didn't seem to work. Either the [instructions](https://github.com/clangd/clangd/blob/master/releases.md) I followed are incomplete, or I'm misunderstanding them.

Hopefully @kadircet can let us know what the missing steps are :)

**Comment by HighCommander4** [comment]
I managed to get release packages for 18.1.3 published at https://github.com/clangd/clangd/releases/tag/18.1.3.

I did it by manually triggering the same Github Action that creates the weekly snapshots, but pointing it at a specific commit on the 18.x branch of llvm-project (the commit tagged as 18.1.3). This is different from what the [instructions](https://github.com/clangd/clangd/blob/master/releases.md#creating-a-release-manually) say (which talk about manually creating a release on the Releases page), but this is what seems to have worked.

**Comment by HighCommander4** [comment]
I documented the steps that worked at https://github.com/clangd/clangd/wiki/Release-checklist#once-the-llvm-release-is-out.

**Comment by philippewarren** [comment]
The release is still marked as a pre-release on GitHub, which causes the clangd VSCode extension to ignore it and still install the 17.0.3 release. Is this intended behavior for the time being, until the release instructions are confirmed?

**Comment by HighCommander4** [comment]
> The release is still marked as a pre-release on GitHub, which causes the clangd VSCode extension to ignore it and still install the 17.0.3 release. Is this intended behavior for the time being, until the release instructions are confirmed?

It was initially intended, but as it's been a week and I haven't come across any issues reported about the 18.1.3, I went ahead an unchecked the "pre-release" checkbox.

**Comment by HighCommander4** [comment]
And I think with that, the checklist is complete and we can close the issue.

**Comment by Scheirle** [comment]
> It was initially intended, but as it's been a week and I haven't come across any issues reported about the 18.1.3 release, I went ahead and unchecked the "pre-release" checkbox.

@HighCommander4 
Is it intentional that 17.0.3 is still tagged as latest release: https://github.com/clangd/clangd/releases/latest ?

**Comment by kadircet** [comment]
updated https://github.com/clangd/clangd/releases/tag/18.1.3 to be the latest and added some steps to do that in https://github.com/clangd/clangd/wiki/Release-checklist

thanks a lot for taking care of this @HighCommander4, sorry for the mess and not noticing this earlier. I need to fix my gmail filters!
