### ISSUE TITLE
Release checklist for clangd 19

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#2127]
Using the [Release checklist](https://github.com/clangd/clangd/wiki/Release-checklist) from the wiki as a template:

## Once the release branch is created

- [x] https://github.com/llvm/llvm-project/pull/105975
- [x] Document new config options added in clangd 19 (already done, the only new option is [`AnalyzeAngledIncludes`](https://clangd.llvm.org/config.html#analyzeangledincludes))
  - [x] https://github.com/SchemaStore/schemastore/issues/4022
- [x] Document any notable new features on the clangd website
  - [x] Documented Modules support in https://github.com/llvm/clangd-www/pull/107

## Once the LLVM release is out

- [x] Prepare the clangd release on the Github releases page
- [x] Mark the release as a stable release by unchecking the "pre-release" checkbox.
- [x] Mark the release as "latest" after a couple weeks if there are no issues.

**Comment by nicovank** [comment]
Should [TidyFastChecks.inc](https://github.com/llvm/llvm-project/blob/675c748bb606d75a959481e6014299849cf3094c/clang-tools-extra/clangd/TidyFastChecks.inc) be updated?

**Comment by HighCommander4** [comment]
> Should [TidyFastChecks.inc](https://github.com/llvm/llvm-project/blob/675c748bb606d75a959481e6014299849cf3094c/clang-tools-extra/clangd/TidyFastChecks.inc) be updated?

I will leave this to @sam-mccall / @kadircet to do at a cadence of their choosing.

**Comment by HighCommander4** [comment]
>   * [ ]  Document any notable new features on the clangd website

The only notable new feature that comes to mind is the initial support for C++20 Modules.

@ChuanqiXu, do you think we should add something to https://clangd.llvm.org/features about it? Or should we wait until the feature is at a more advanced stage?

**Comment by ChuanqiXu9** [comment]
> > * [ ]   Document any notable new features on the clangd website
> 
> The only notable new feature that comes to mind is the initial support for C++20 Modules.
> 
> @ChuanqiXu9, do you think we should add something to https://clangd.llvm.org/features about it? Or should we wait until the feature is at a more advanced stage?

I think we should add it. It will pretty helpful for us to improve this by receiving more issue reports.

**Comment by HighCommander4** [comment]
> > The only notable new feature that comes to mind is the initial support for C++20 Modules.
> > @ChuanqiXu9, do you think we should add something to https://clangd.llvm.org/features about it? Or should we wait until the feature is at a more advanced stage?
> 
> I think we should add it. It will pretty helpful for us to improve this by receiving more issue reports.

Makes sense. Would you like to send a PR? The page source is at https://github.com/llvm/clangd-www/blob/main/features.md.

**Comment by ChuanqiXu9** [comment]
> > > The only notable new feature that comes to mind is the initial support for C++20 Modules.
> > > @ChuanqiXu9, do you think we should add something to https://clangd.llvm.org/features about it? Or should we wait until the feature is at a more advanced stage?
> > 
> > 
> > I think we should add it. It will pretty helpful for us to improve this by receiving more issue reports.
> 
> Makes sense. Would you like to send a PR? The page source is at https://github.com/llvm/clangd-www/blob/main/features.md.

I sent it here: https://github.com/llvm/clangd-www/pull/107

**Comment by kadircet** [comment]
> > Should [TidyFastChecks.inc](https://github.com/llvm/llvm-project/blob/675c748bb606d75a959481e6014299849cf3094c/clang-tools-extra/clangd/TidyFastChecks.inc) be updated?
> 
> I will leave this to @sam-mccall / @kadircet to do at a cadence of their choosing.

thanks for the ping! https://github.com/llvm/llvm-project/pull/106354 for analysis at 19.x, we should also get that cherry-picked to release branch

**Comment by HighCommander4** [comment]
I've prepared a 19.1.0 release at https://github.com/clangd/clangd/releases/tag/19.1.0. Marked as pre-release for now, testing is welcome.

**Comment by HighCommander4** [comment]
I've now unchecked the pre-release checkbox.

**Comment by HighCommander4** [comment]
Note that a crash regression affecting 19.1.0 has been found and fixed on trunk in https://github.com/llvm/llvm-project/issues/109367. I've proposed backporting the fix to the 19.x branch in https://github.com/llvm/llvm-project/issues/111317.

I would like to wait for that fix to appear in a release before marking a 19.x release as "latest".

**Comment by amitrahman1026** [comment]
> Note that a crash regression affecting 19.1.0 has been found and fixed on trunk in [llvm/llvm-project#109367](https://github.com/llvm/llvm-project/issues/109367). I've proposed backporting the fix to the 19.x branch in [llvm/llvm-project#111317](https://github.com/llvm/llvm-project/issues/111317).
> 
> I would like to wait for that fix to appear in a release before marking a 19.x release as "latest".

I've also noted the aforementioned bug, where I talked about it [here (with backtrace logs)](https://github.com/erigontech/silkworm/issues/2408#issuecomment-2407201912) but on `Homebrew clangd version 19.1.1`. I'm a little confused about this 19.x release terminology as I'm new to looking at llvm's release structure, but does that mean I should be looking out for the next release version?

**Comment by HighCommander4** [comment]
> I've also encountered the aforementioned bug, where I talked about it [here (with backtrace logs)](https://github.com/erigontech/silkworm/issues/2408#issuecomment-2407201912) but on `Homebrew clangd version 19.1.1`. I'm a little confused about this 19.x release terminology as I'm new to looking at llvm's release structure, but does that mean I should be looking out for the next release version?

Yes, 19.1.1 is affected as well.

The backport of this fix to the 19.x branch was just merged within the past day (https://github.com/llvm/llvm-project/pull/111318), so it will appear in the next dot release. According to [this thread](https://discourse.llvm.org/t/llvm-19-1-1-released/82321), that should be 19.1.2 around Oct 15.

Until then, I suggest using clangd 18. It can be obtained from https://github.com/clangd/clangd/releases/tag/18.1.3.

**Comment by HighCommander4** [comment]
A 19.1.2 release is now up at https://github.com/clangd/clangd/releases/tag/19.1.2.

**Comment by HighCommander4** [comment]
> A 19.1.2 release is now up at https://github.com/clangd/clangd/releases/tag/19.1.2.

I just realized this was still marked as "pre-release"; unchecked that now.

Are we ready to mark this "latest"?

**Comment by HighCommander4** [comment]
> Are we ready to mark this as "latest"?

Forgot to circle back to this and tick the "latest" checkbox. Done now.
