### ISSUE TITLE
Patches to cherrypick for release 10.0.1

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#417]
- [x] Fix null check in FindTarget. https://github.com/llvm/llvm-project/commit/9a5c448a31bacc08e73fcae4636094f9b6e2be6a, #414 
- [x] [clangd] Increase stack size of the new threads on macOS https://github.com/llvm/llvm-project/commit/69a39dc1f0d08ea43bac03a87bb8bff3937ce2e7 
- [x] [clangd] Don't assert when completing a lambda variable inside the lambda llvm/llvm-project@2629035a009095f62f48413e175437261165ecd7
- [x] [clangd] Add the missing elaborated types in FindTarget.  llvm/llvm-project@eaf0c89ec5f866b6cef296c542c030bb2cf8481d #415 
-  <s> [clangd] Fix a crash for accessing a null field decl returned by findExplicitReferences, llvm/llvm-project@6a78c55e3af0fc98513bf7e0b76b3b88719ca2c3 </s>
- [x] [clangd] Fix a crash for accessing a null template decl llvm/llvm-project@7d1ee639cb9efea364bec90afe4d1161ec624a7f
- [x] [clangd] Fix modernize-loop-convert "multiple diag in flight" crash. llvm/llvm-project@a466e4be3831848d7ff6ffbe4f57d99de8fb66af
- [x] [clang] Fix crash on visiting null nestedNameSpecifier. llvm/llvm-project@bd763e2cf7c1d84bab95064cc5cbe542b227b025, llvm/llvm-project@44c3a63c74dddeef17e424ec76bd90c8582d8a3c
- <s> [AST] Fix an assertion violation in FieldDecl::getParent. llvm/llvm-project@fcf0764998b45279cfdf4039c69aec2cd09051a5 </s>
- [x] [clang] Persist Attr::IsPackExpansion into the PCH, llvm/llvm-project@8b3b7556e9ab6084e9fd337d64dac1c165867d32
- [x] [Syntax] Merge overlapping top-level macros in TokenBuffer, llvm/llvm-project@d66afd6, #416 
- [x] patches (???) for windows improvements, #321

**Comment by sam-mccall** [comment]
> patches (???) for windows improvements, #321

https://github.com/llvm/llvm-project/commit/294b9d43cae77ea15453ec82203368903db4f538

(maybe others)

**Comment by sam-mccall** [comment]
Closing this as they're all merged.
